# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import structlog
from fastapi import APIRouter
from fastapi import status
from pydantic import parse_obj_as

from os2mint_omada import depends
from os2mint_omada.autogenerated_graphql_client import EventSendInput
from os2mint_omada.omada.event_generator import OMADA_NAMESPACE
from os2mint_omada.omada.event_generator import OMADA_ROUTING_KEY
from os2mint_omada.omada.models import OmadaUser
from os2mint_omada.omada.models import RawOmadaUser

router = APIRouter()
logger = structlog.stdlib.get_logger()


@router.post("/sync/omada", status_code=status.HTTP_204_NO_CONTENT)
async def sync_omada(
    omada_api: depends.OmadaAPI,
    graphql_client: depends.GraphQLClient,
    subject_builder: depends.SubjectBuilder,
    omada_filter: str | None = None,
) -> None:
    """Force-synchronise Omada user(s) matching the given Omada filter."""
    logger.info("Synchronising Omada users", omada_filter=omada_filter)
    raw_omada_users = await omada_api.get_users(omada_filter)
    logger.info("Synchronising raw Omada users", omada_users=raw_omada_users)
    omada_users = parse_obj_as(list[OmadaUser], raw_omada_users)
    for omada_user in omada_users:
        await graphql_client.send_event(
            input=EventSendInput(
                namespace=OMADA_NAMESPACE,
                routing_key=OMADA_ROUTING_KEY,
                subject=subject_builder(omada_user).json(),
            )
        )


@router.get("/get-users")
async def get_users(
    omada_api: depends.OmadaAPI, omada_filter: str | None = None
) -> list[RawOmadaUser]:
    """Get Omada user(s) matching the given Omada filter."""
    raw_omada_users = await omada_api.get_users(omada_filter)
    return raw_omada_users
