# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from collections.abc import Callable
from typing import Annotated

from fastapi import Depends
from fastramqpi.depends import from_user_context
from fastramqpi.events import Event
from fastramqpi.ramqp.depends import from_context
from more_itertools import only
from pydantic import Json
from pydantic import parse_obj_as

from os2mint_omada.autogenerated_graphql_client import GraphQLClient as _GraphQLClient
from os2mint_omada.mo import MO as _MO
from os2mint_omada.omada.api import OmadaAPI as _OmadaAPI
from os2mint_omada.omada.models import OmadaEventSubject
from os2mint_omada.omada.models import OmadaUser

GraphQLClient = Annotated[_GraphQLClient, Depends(from_context("graphql_client"))]

# Omada context
OmadaAPI = Annotated[_OmadaAPI, Depends(from_user_context("omada_api"))]
SubjectBuilder = Annotated[
    Callable[[OmadaUser], OmadaEventSubject],
    Depends(from_user_context("subject_builder")),
]


async def current_omada_user(
    event: Event[Json[OmadaEventSubject]],
    omada_api: OmadaAPI,
) -> OmadaUser | None:
    """Return the latest state of the Omada user named by the event.

    Handlers should always use the latest data from the API rather than data
    embedded in the event, e.g. if the user was created with an invalid
    CPR-number and later corrected. `None` is returned if the user no longer
    exists in the Omada view (i.e. it has been deleted).
    """
    # NOTE: Old versions of Omada (i.e. the version our customers use) do not support filtering on UId, so we filter on Id instead.
    api_users_raw = await omada_api.get_users_by("Id", [event.subject.id])
    if not api_users_raw:
        return None
    return parse_obj_as(OmadaUser, only(api_users_raw))


CurrentOmadaUser = Annotated[OmadaUser | None, Depends(current_omada_user)]


def get_mo(graphql_client: GraphQLClient) -> _MO:
    return _MO(graphql_client)


MO = Annotated[_MO, Depends(get_mo)]
