# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from typing import Annotated

from fastapi import Depends
from fastramqpi.depends import from_user_context
from fastramqpi.ramqp import AMQPSystem
from fastramqpi.ramqp.depends import from_context

from os2mint_omada.autogenerated_graphql_client import GraphQLClient as _GraphQLClient
from os2mint_omada.mo import MO as _MO
from os2mint_omada.omada.api import OmadaAPI as _OmadaAPI

GraphQLClient = Annotated[_GraphQLClient, Depends(from_context("graphql_client"))]

# Omada context
MO = Annotated[_MO, Depends(from_user_context("mo"))]
OmadaAMQPSystem = Annotated[AMQPSystem, Depends(from_user_context("omada_amqp_system"))]
OmadaAPI = Annotated[_OmadaAPI, Depends(from_user_context("omada_api"))]
