import asyncio
from datetime import datetime
from uuid import UUID

from pydantic import AnyHttpUrl
from pydantic import parse_obj_as
from raclients.auth import AuthenticatedAsyncHTTPXClient
from raclients.auth import keycloak_token_endpoint

from os2mint_omada.autogenerated_graphql_client.client import Client

auth = AuthenticatedAsyncHTTPXClient(
    client_id="dipex",
    client_secret="603f1c82-d012-4d04-9382-dbe659c533fb",
    token_endpoint=keycloak_token_endpoint(
        auth_server=parse_obj_as(AnyHttpUrl, "http://localhost:5000/auth"),
        auth_realm="mo",
    ),
)

client = Client(
    url="http://localhost:5000/graphql/v7",
    http_client=auth,
)


async def main():
    res = await client.get_employees(limit=5)
    for e in res.objects:
        current = e.current
        print(current.uuid, current.cpr_no)
        it_user = await client.create_i_t_user(
            itsystem=UUID("1760947e-0496-1483-fba8-98af2b98ef4f"),
            person=current.uuid,
            user_key=current.cpr_no,
            from_=datetime.now(),
        )
        print(it_user.uuid)


asyncio.run(main())
