# Generated by ariadne-codegen on 2024-08-22 18:07

from ._testing__create_employee import TestingCreateEmployee
from ._testing__create_employee import TestingCreateEmployeeEmployeeCreate
from ._testing__create_org_unit import TestingCreateOrgUnit
from ._testing__create_org_unit import TestingCreateOrgUnitOrgUnitCreate
from ._testing__create_org_unit_it_user import TestingCreateOrgUnitItUser
from ._testing__create_org_unit_it_user import TestingCreateOrgUnitItUserItuserCreate
from ._testing__get_employee import TestingGetEmployee
from ._testing__get_employee import TestingGetEmployeeEmployees
from ._testing__get_employee import TestingGetEmployeeEmployeesObjects
from ._testing__get_employee import TestingGetEmployeeEmployeesObjectsValidities
from ._testing__get_employee import (
    TestingGetEmployeeEmployeesObjectsValiditiesAddresses,
)
from ._testing__get_employee import (
    TestingGetEmployeeEmployeesObjectsValiditiesAddressesAddressType,
)
from ._testing__get_employee import (
    TestingGetEmployeeEmployeesObjectsValiditiesAddressesEngagement,
)
from ._testing__get_employee import (
    TestingGetEmployeeEmployeesObjectsValiditiesAddressesValidity,
)
from ._testing__get_employee import (
    TestingGetEmployeeEmployeesObjectsValiditiesAddressesVisibility,
)
from ._testing__get_employee import (
    TestingGetEmployeeEmployeesObjectsValiditiesEngagements,
)
from ._testing__get_employee import (
    TestingGetEmployeeEmployeesObjectsValiditiesEngagementsEngagementType,
)
from ._testing__get_employee import (
    TestingGetEmployeeEmployeesObjectsValiditiesEngagementsJobFunction,
)
from ._testing__get_employee import (
    TestingGetEmployeeEmployeesObjectsValiditiesEngagementsOrgUnit,
)
from ._testing__get_employee import (
    TestingGetEmployeeEmployeesObjectsValiditiesEngagementsPrimary,
)
from ._testing__get_employee import (
    TestingGetEmployeeEmployeesObjectsValiditiesEngagementsValidity,
)
from ._testing__get_employee import TestingGetEmployeeEmployeesObjectsValiditiesItusers
from ._testing__get_employee import (
    TestingGetEmployeeEmployeesObjectsValiditiesItusersEngagement,
)
from ._testing__get_employee import (
    TestingGetEmployeeEmployeesObjectsValiditiesItusersItsystem,
)
from ._testing__get_employee import (
    TestingGetEmployeeEmployeesObjectsValiditiesItusersValidity,
)
from ._testing__get_employee import TestingGetEmployeeEmployeesObjectsValiditiesValidity
from ._testing__get_it_system import TestingGetItSystem
from ._testing__get_it_system import TestingGetItSystemItsystems
from ._testing__get_it_system import TestingGetItSystemItsystemsObjects
from ._testing__get_org_unit_type import TestingGetOrgUnitType
from ._testing__get_org_unit_type import TestingGetOrgUnitTypeClasses
from ._testing__get_org_unit_type import TestingGetOrgUnitTypeClassesObjects
from .async_base_client import AsyncBaseClient
from .base_model import BaseModel
from .client import GraphQLClient
from .create_address import CreateAddress
from .create_address import CreateAddressAddressCreate
from .create_employee import CreateEmployee
from .create_employee import CreateEmployeeEmployeeCreate
from .create_engagement import CreateEngagement
from .create_engagement import CreateEngagementEngagementCreate
from .create_it_user import CreateItUser
from .create_it_user import CreateItUserItuserCreate
from .delete_address import DeleteAddress
from .delete_address import DeleteAddressAddressDelete
from .delete_engagement import DeleteEngagement
from .delete_engagement import DeleteEngagementEngagementDelete
from .delete_it_user import DeleteItUser
from .delete_it_user import DeleteItUserItuserDelete
from .enums import AuditLogModel
from .enums import FileStore
from .enums import OwnerInferencePriority
from .exceptions import GraphQLClientError
from .exceptions import GraphQLClientGraphQLError
from .exceptions import GraphQLClientGraphQLMultiError
from .exceptions import GraphQLClientHttpError
from .exceptions import GraphQlClientInvalidResponseError
from .get_classes import GetClasses
from .get_classes import GetClassesFacets
from .get_classes import GetClassesFacetsObjects
from .get_classes import GetClassesFacetsObjectsCurrent
from .get_classes import GetClassesFacetsObjectsCurrentClasses
from .get_current_employee_state import GetCurrentEmployeeState
from .get_current_employee_state import GetCurrentEmployeeStateEmployees
from .get_current_employee_state import GetCurrentEmployeeStateEmployeesObjects
from .get_current_employee_state import GetCurrentEmployeeStateEmployeesObjectsCurrent
from .get_employee_addresses import GetEmployeeAddresses
from .get_employee_addresses import GetEmployeeAddressesEmployees
from .get_employee_addresses import GetEmployeeAddressesEmployeesObjects
from .get_employee_addresses import GetEmployeeAddressesEmployeesObjectsValidities
from .get_employee_addresses import (
    GetEmployeeAddressesEmployeesObjectsValiditiesAddresses,
)
from .get_employee_addresses import (
    GetEmployeeAddressesEmployeesObjectsValiditiesAddressesAddressType,
)
from .get_employee_addresses import (
    GetEmployeeAddressesEmployeesObjectsValiditiesAddressesEngagement,
)
from .get_employee_addresses import (
    GetEmployeeAddressesEmployeesObjectsValiditiesAddressesPerson,
)
from .get_employee_addresses import (
    GetEmployeeAddressesEmployeesObjectsValiditiesAddressesValidity,
)
from .get_employee_addresses import (
    GetEmployeeAddressesEmployeesObjectsValiditiesAddressesVisibility,
)
from .get_employee_engagements import GetEmployeeEngagements
from .get_employee_engagements import GetEmployeeEngagementsEmployees
from .get_employee_engagements import GetEmployeeEngagementsEmployeesObjects
from .get_employee_engagements import GetEmployeeEngagementsEmployeesObjectsValidities
from .get_employee_engagements import (
    GetEmployeeEngagementsEmployeesObjectsValiditiesEngagements,
)
from .get_employee_engagements import (
    GetEmployeeEngagementsEmployeesObjectsValiditiesEngagementsEngagementType,
)
from .get_employee_engagements import (
    GetEmployeeEngagementsEmployeesObjectsValiditiesEngagementsJobFunction,
)
from .get_employee_engagements import (
    GetEmployeeEngagementsEmployeesObjectsValiditiesEngagementsOrgUnit,
)
from .get_employee_engagements import (
    GetEmployeeEngagementsEmployeesObjectsValiditiesEngagementsPerson,
)
from .get_employee_engagements import (
    GetEmployeeEngagementsEmployeesObjectsValiditiesEngagementsPrimary,
)
from .get_employee_engagements import (
    GetEmployeeEngagementsEmployeesObjectsValiditiesEngagementsValidity,
)
from .get_employee_it_users import GetEmployeeItUsers
from .get_employee_it_users import GetEmployeeItUsersEmployees
from .get_employee_it_users import GetEmployeeItUsersEmployeesObjects
from .get_employee_it_users import GetEmployeeItUsersEmployeesObjectsValidities
from .get_employee_it_users import GetEmployeeItUsersEmployeesObjectsValiditiesItusers
from .get_employee_it_users import (
    GetEmployeeItUsersEmployeesObjectsValiditiesItusersEngagement,
)
from .get_employee_it_users import (
    GetEmployeeItUsersEmployeesObjectsValiditiesItusersItsystem,
)
from .get_employee_it_users import (
    GetEmployeeItUsersEmployeesObjectsValiditiesItusersPerson,
)
from .get_employee_it_users import (
    GetEmployeeItUsersEmployeesObjectsValiditiesItusersValidity,
)
from .get_employee_states import GetEmployeeStates
from .get_employee_states import GetEmployeeStatesEmployees
from .get_employee_states import GetEmployeeStatesEmployeesObjects
from .get_employee_states import GetEmployeeStatesEmployeesObjectsValidities
from .get_employee_uuid_from_cpr import GetEmployeeUuidFromCpr
from .get_employee_uuid_from_cpr import GetEmployeeUuidFromCprEmployees
from .get_employee_uuid_from_cpr import GetEmployeeUuidFromCprEmployeesObjects
from .get_employee_uuid_from_user_key import GetEmployeeUuidFromUserKey
from .get_employee_uuid_from_user_key import GetEmployeeUuidFromUserKeyEngagements
from .get_employee_uuid_from_user_key import (
    GetEmployeeUuidFromUserKeyEngagementsObjects,
)
from .get_employee_uuid_from_user_key import (
    GetEmployeeUuidFromUserKeyEngagementsObjectsValidities,
)
from .get_employee_uuid_from_user_key import (
    GetEmployeeUuidFromUserKeyEngagementsObjectsValiditiesPerson,
)
from .get_it_systems import GetItSystems
from .get_it_systems import GetItSystemsItsystems
from .get_it_systems import GetItSystemsItsystemsObjects
from .get_it_systems import GetItSystemsItsystemsObjectsCurrent
from .get_org_unit_validity import GetOrgUnitValidity
from .get_org_unit_validity import GetOrgUnitValidityOrgUnits
from .get_org_unit_validity import GetOrgUnitValidityOrgUnitsObjects
from .get_org_unit_validity import GetOrgUnitValidityOrgUnitsObjectsValidities
from .get_org_unit_validity import GetOrgUnitValidityOrgUnitsObjectsValiditiesValidity
from .get_org_unit_with_it_system_user_key import GetOrgUnitWithItSystemUserKey
from .get_org_unit_with_it_system_user_key import GetOrgUnitWithItSystemUserKeyItusers
from .get_org_unit_with_it_system_user_key import (
    GetOrgUnitWithItSystemUserKeyItusersObjects,
)
from .get_org_unit_with_it_system_user_key import (
    GetOrgUnitWithItSystemUserKeyItusersObjectsValidities,
)
from .get_org_unit_with_it_system_user_key import (
    GetOrgUnitWithItSystemUserKeyItusersObjectsValiditiesOrgUnit,
)
from .get_org_unit_with_user_key import GetOrgUnitWithUserKey
from .get_org_unit_with_user_key import GetOrgUnitWithUserKeyOrgUnits
from .get_org_unit_with_user_key import GetOrgUnitWithUserKeyOrgUnitsObjects
from .get_org_unit_with_uuid import GetOrgUnitWithUuid
from .get_org_unit_with_uuid import GetOrgUnitWithUuidOrgUnits
from .get_org_unit_with_uuid import GetOrgUnitWithUuidOrgUnitsObjects
from .input_types import AddressCreateInput
from .input_types import AddressFilter
from .input_types import AddressRegistrationFilter
from .input_types import AddressTerminateInput
from .input_types import AddressUpdateInput
from .input_types import AssociationCreateInput
from .input_types import AssociationFilter
from .input_types import AssociationRegistrationFilter
from .input_types import AssociationTerminateInput
from .input_types import AssociationUpdateInput
from .input_types import AuditLogFilter
from .input_types import ClassCreateInput
from .input_types import ClassFilter
from .input_types import ClassRegistrationFilter
from .input_types import ClassTerminateInput
from .input_types import ClassUpdateInput
from .input_types import ConfigurationFilter
from .input_types import EmployeeCreateInput
from .input_types import EmployeeFilter
from .input_types import EmployeeRegistrationFilter
from .input_types import EmployeesBoundAddressFilter
from .input_types import EmployeesBoundAssociationFilter
from .input_types import EmployeesBoundEngagementFilter
from .input_types import EmployeesBoundITUserFilter
from .input_types import EmployeesBoundLeaveFilter
from .input_types import EmployeesBoundManagerFilter
from .input_types import EmployeeTerminateInput
from .input_types import EmployeeUpdateInput
from .input_types import EngagementCreateInput
from .input_types import EngagementFilter
from .input_types import EngagementRegistrationFilter
from .input_types import EngagementTerminateInput
from .input_types import EngagementUpdateInput
from .input_types import FacetCreateInput
from .input_types import FacetFilter
from .input_types import FacetRegistrationFilter
from .input_types import FacetsBoundClassFilter
from .input_types import FacetTerminateInput
from .input_types import FacetUpdateInput
from .input_types import FileFilter
from .input_types import HealthFilter
from .input_types import ITAssociationCreateInput
from .input_types import ITAssociationTerminateInput
from .input_types import ITAssociationUpdateInput
from .input_types import ITSystemCreateInput
from .input_types import ITSystemFilter
from .input_types import ITSystemRegistrationFilter
from .input_types import ITSystemTerminateInput
from .input_types import ITSystemUpdateInput
from .input_types import ItuserBoundAddressFilter
from .input_types import ItuserBoundRoleBindingFilter
from .input_types import ITUserCreateInput
from .input_types import ITUserFilter
from .input_types import ITUserRegistrationFilter
from .input_types import ITUserTerminateInput
from .input_types import ITUserUpdateInput
from .input_types import KLECreateInput
from .input_types import KLEFilter
from .input_types import KLERegistrationFilter
from .input_types import KLETerminateInput
from .input_types import KLEUpdateInput
from .input_types import LeaveCreateInput
from .input_types import LeaveFilter
from .input_types import LeaveRegistrationFilter
from .input_types import LeaveTerminateInput
from .input_types import LeaveUpdateInput
from .input_types import ManagerCreateInput
from .input_types import ManagerFilter
from .input_types import ManagerRegistrationFilter
from .input_types import ManagerTerminateInput
from .input_types import ManagerUpdateInput
from .input_types import ModelsUuidsBoundRegistrationFilter
from .input_types import OrganisationCreate
from .input_types import OrganisationUnitCreateInput
from .input_types import OrganisationUnitFilter
from .input_types import OrganisationUnitRegistrationFilter
from .input_types import OrganisationUnitTerminateInput
from .input_types import OrganisationUnitUpdateInput
from .input_types import OrgUnitsboundaddressfilter
from .input_types import OrgUnitsboundassociationfilter
from .input_types import OrgUnitsboundengagementfilter
from .input_types import OrgUnitsboundituserfilter
from .input_types import OrgUnitsboundklefilter
from .input_types import OrgUnitsboundleavefilter
from .input_types import OrgUnitsboundrelatedunitfilter
from .input_types import OwnerCreateInput
from .input_types import OwnerFilter
from .input_types import OwnerTerminateInput
from .input_types import OwnerUpdateInput
from .input_types import ParentsBoundClassFilter
from .input_types import ParentsBoundFacetFilter
from .input_types import ParentsBoundOrganisationUnitFilter
from .input_types import RAOpenValidityInput
from .input_types import RAValidityInput
from .input_types import RegistrationFilter
from .input_types import RelatedUnitFilter
from .input_types import RelatedUnitsUpdateInput
from .input_types import RoleBindingCreateInput
from .input_types import RoleBindingFilter
from .input_types import RoleBindingTerminateInput
from .input_types import RoleBindingUpdateInput
from .input_types import RoleRegistrationFilter
from .input_types import UuidsBoundClassFilter
from .input_types import UuidsBoundEmployeeFilter
from .input_types import UuidsBoundEngagementFilter
from .input_types import UuidsBoundFacetFilter
from .input_types import UuidsBoundITSystemFilter
from .input_types import UuidsBoundITUserFilter
from .input_types import UuidsBoundLeaveFilter
from .input_types import UuidsBoundOrganisationUnitFilter
from .input_types import ValidityInput

__all__ = [
    "AddressCreateInput",
    "AddressFilter",
    "AddressRegistrationFilter",
    "AddressTerminateInput",
    "AddressUpdateInput",
    "AssociationCreateInput",
    "AssociationFilter",
    "AssociationRegistrationFilter",
    "AssociationTerminateInput",
    "AssociationUpdateInput",
    "AsyncBaseClient",
    "AuditLogFilter",
    "AuditLogModel",
    "BaseModel",
    "ClassCreateInput",
    "ClassFilter",
    "ClassRegistrationFilter",
    "ClassTerminateInput",
    "ClassUpdateInput",
    "ConfigurationFilter",
    "CreateAddress",
    "CreateAddressAddressCreate",
    "CreateEmployee",
    "CreateEmployeeEmployeeCreate",
    "CreateEngagement",
    "CreateEngagementEngagementCreate",
    "CreateItUser",
    "CreateItUserItuserCreate",
    "DeleteAddress",
    "DeleteAddressAddressDelete",
    "DeleteEngagement",
    "DeleteEngagementEngagementDelete",
    "DeleteItUser",
    "DeleteItUserItuserDelete",
    "EmployeeCreateInput",
    "EmployeeFilter",
    "EmployeeRegistrationFilter",
    "EmployeeTerminateInput",
    "EmployeeUpdateInput",
    "EmployeesBoundAddressFilter",
    "EmployeesBoundAssociationFilter",
    "EmployeesBoundEngagementFilter",
    "EmployeesBoundITUserFilter",
    "EmployeesBoundLeaveFilter",
    "EmployeesBoundManagerFilter",
    "EngagementCreateInput",
    "EngagementFilter",
    "EngagementRegistrationFilter",
    "EngagementTerminateInput",
    "EngagementUpdateInput",
    "FacetCreateInput",
    "FacetFilter",
    "FacetRegistrationFilter",
    "FacetTerminateInput",
    "FacetUpdateInput",
    "FacetsBoundClassFilter",
    "FileFilter",
    "FileStore",
    "GetClasses",
    "GetClassesFacets",
    "GetClassesFacetsObjects",
    "GetClassesFacetsObjectsCurrent",
    "GetClassesFacetsObjectsCurrentClasses",
    "GetCurrentEmployeeState",
    "GetCurrentEmployeeStateEmployees",
    "GetCurrentEmployeeStateEmployeesObjects",
    "GetCurrentEmployeeStateEmployeesObjectsCurrent",
    "GetEmployeeAddresses",
    "GetEmployeeAddressesEmployees",
    "GetEmployeeAddressesEmployeesObjects",
    "GetEmployeeAddressesEmployeesObjectsValidities",
    "GetEmployeeAddressesEmployeesObjectsValiditiesAddresses",
    "GetEmployeeAddressesEmployeesObjectsValiditiesAddressesAddressType",
    "GetEmployeeAddressesEmployeesObjectsValiditiesAddressesEngagement",
    "GetEmployeeAddressesEmployeesObjectsValiditiesAddressesPerson",
    "GetEmployeeAddressesEmployeesObjectsValiditiesAddressesValidity",
    "GetEmployeeAddressesEmployeesObjectsValiditiesAddressesVisibility",
    "GetEmployeeEngagements",
    "GetEmployeeEngagementsEmployees",
    "GetEmployeeEngagementsEmployeesObjects",
    "GetEmployeeEngagementsEmployeesObjectsValidities",
    "GetEmployeeEngagementsEmployeesObjectsValiditiesEngagements",
    "GetEmployeeEngagementsEmployeesObjectsValiditiesEngagementsEngagementType",
    "GetEmployeeEngagementsEmployeesObjectsValiditiesEngagementsJobFunction",
    "GetEmployeeEngagementsEmployeesObjectsValiditiesEngagementsOrgUnit",
    "GetEmployeeEngagementsEmployeesObjectsValiditiesEngagementsPerson",
    "GetEmployeeEngagementsEmployeesObjectsValiditiesEngagementsPrimary",
    "GetEmployeeEngagementsEmployeesObjectsValiditiesEngagementsValidity",
    "GetEmployeeItUsers",
    "GetEmployeeItUsersEmployees",
    "GetEmployeeItUsersEmployeesObjects",
    "GetEmployeeItUsersEmployeesObjectsValidities",
    "GetEmployeeItUsersEmployeesObjectsValiditiesItusers",
    "GetEmployeeItUsersEmployeesObjectsValiditiesItusersEngagement",
    "GetEmployeeItUsersEmployeesObjectsValiditiesItusersItsystem",
    "GetEmployeeItUsersEmployeesObjectsValiditiesItusersPerson",
    "GetEmployeeItUsersEmployeesObjectsValiditiesItusersValidity",
    "GetEmployeeStates",
    "GetEmployeeStatesEmployees",
    "GetEmployeeStatesEmployeesObjects",
    "GetEmployeeStatesEmployeesObjectsValidities",
    "GetEmployeeUuidFromCpr",
    "GetEmployeeUuidFromCprEmployees",
    "GetEmployeeUuidFromCprEmployeesObjects",
    "GetEmployeeUuidFromUserKey",
    "GetEmployeeUuidFromUserKeyEngagements",
    "GetEmployeeUuidFromUserKeyEngagementsObjects",
    "GetEmployeeUuidFromUserKeyEngagementsObjectsValidities",
    "GetEmployeeUuidFromUserKeyEngagementsObjectsValiditiesPerson",
    "GetItSystems",
    "GetItSystemsItsystems",
    "GetItSystemsItsystemsObjects",
    "GetItSystemsItsystemsObjectsCurrent",
    "GetOrgUnitValidity",
    "GetOrgUnitValidityOrgUnits",
    "GetOrgUnitValidityOrgUnitsObjects",
    "GetOrgUnitValidityOrgUnitsObjectsValidities",
    "GetOrgUnitValidityOrgUnitsObjectsValiditiesValidity",
    "GetOrgUnitWithItSystemUserKey",
    "GetOrgUnitWithItSystemUserKeyItusers",
    "GetOrgUnitWithItSystemUserKeyItusersObjects",
    "GetOrgUnitWithItSystemUserKeyItusersObjectsValidities",
    "GetOrgUnitWithItSystemUserKeyItusersObjectsValiditiesOrgUnit",
    "GetOrgUnitWithUserKey",
    "GetOrgUnitWithUserKeyOrgUnits",
    "GetOrgUnitWithUserKeyOrgUnitsObjects",
    "GetOrgUnitWithUuid",
    "GetOrgUnitWithUuidOrgUnits",
    "GetOrgUnitWithUuidOrgUnitsObjects",
    "GraphQLClient",
    "GraphQLClientError",
    "GraphQLClientGraphQLError",
    "GraphQLClientGraphQLMultiError",
    "GraphQLClientHttpError",
    "GraphQlClientInvalidResponseError",
    "HealthFilter",
    "ITAssociationCreateInput",
    "ITAssociationTerminateInput",
    "ITAssociationUpdateInput",
    "ITSystemCreateInput",
    "ITSystemFilter",
    "ITSystemRegistrationFilter",
    "ITSystemTerminateInput",
    "ITSystemUpdateInput",
    "ITUserCreateInput",
    "ITUserFilter",
    "ITUserRegistrationFilter",
    "ITUserTerminateInput",
    "ITUserUpdateInput",
    "ItuserBoundAddressFilter",
    "ItuserBoundRoleBindingFilter",
    "KLECreateInput",
    "KLEFilter",
    "KLERegistrationFilter",
    "KLETerminateInput",
    "KLEUpdateInput",
    "LeaveCreateInput",
    "LeaveFilter",
    "LeaveRegistrationFilter",
    "LeaveTerminateInput",
    "LeaveUpdateInput",
    "ManagerCreateInput",
    "ManagerFilter",
    "ManagerRegistrationFilter",
    "ManagerTerminateInput",
    "ManagerUpdateInput",
    "ModelsUuidsBoundRegistrationFilter",
    "OrgUnitsboundaddressfilter",
    "OrgUnitsboundassociationfilter",
    "OrgUnitsboundengagementfilter",
    "OrgUnitsboundituserfilter",
    "OrgUnitsboundklefilter",
    "OrgUnitsboundleavefilter",
    "OrgUnitsboundrelatedunitfilter",
    "OrganisationCreate",
    "OrganisationUnitCreateInput",
    "OrganisationUnitFilter",
    "OrganisationUnitRegistrationFilter",
    "OrganisationUnitTerminateInput",
    "OrganisationUnitUpdateInput",
    "OwnerCreateInput",
    "OwnerFilter",
    "OwnerInferencePriority",
    "OwnerTerminateInput",
    "OwnerUpdateInput",
    "ParentsBoundClassFilter",
    "ParentsBoundFacetFilter",
    "ParentsBoundOrganisationUnitFilter",
    "RAOpenValidityInput",
    "RAValidityInput",
    "RegistrationFilter",
    "RelatedUnitFilter",
    "RelatedUnitsUpdateInput",
    "RoleBindingCreateInput",
    "RoleBindingFilter",
    "RoleBindingTerminateInput",
    "RoleBindingUpdateInput",
    "RoleRegistrationFilter",
    "TestingCreateEmployee",
    "TestingCreateEmployeeEmployeeCreate",
    "TestingCreateOrgUnit",
    "TestingCreateOrgUnitItUser",
    "TestingCreateOrgUnitItUserItuserCreate",
    "TestingCreateOrgUnitOrgUnitCreate",
    "TestingGetEmployee",
    "TestingGetEmployeeEmployees",
    "TestingGetEmployeeEmployeesObjects",
    "TestingGetEmployeeEmployeesObjectsValidities",
    "TestingGetEmployeeEmployeesObjectsValiditiesAddresses",
    "TestingGetEmployeeEmployeesObjectsValiditiesAddressesAddressType",
    "TestingGetEmployeeEmployeesObjectsValiditiesAddressesEngagement",
    "TestingGetEmployeeEmployeesObjectsValiditiesAddressesValidity",
    "TestingGetEmployeeEmployeesObjectsValiditiesAddressesVisibility",
    "TestingGetEmployeeEmployeesObjectsValiditiesEngagements",
    "TestingGetEmployeeEmployeesObjectsValiditiesEngagementsEngagementType",
    "TestingGetEmployeeEmployeesObjectsValiditiesEngagementsJobFunction",
    "TestingGetEmployeeEmployeesObjectsValiditiesEngagementsOrgUnit",
    "TestingGetEmployeeEmployeesObjectsValiditiesEngagementsPrimary",
    "TestingGetEmployeeEmployeesObjectsValiditiesEngagementsValidity",
    "TestingGetEmployeeEmployeesObjectsValiditiesItusers",
    "TestingGetEmployeeEmployeesObjectsValiditiesItusersEngagement",
    "TestingGetEmployeeEmployeesObjectsValiditiesItusersItsystem",
    "TestingGetEmployeeEmployeesObjectsValiditiesItusersValidity",
    "TestingGetEmployeeEmployeesObjectsValiditiesValidity",
    "TestingGetItSystem",
    "TestingGetItSystemItsystems",
    "TestingGetItSystemItsystemsObjects",
    "TestingGetOrgUnitType",
    "TestingGetOrgUnitTypeClasses",
    "TestingGetOrgUnitTypeClassesObjects",
    "UuidsBoundClassFilter",
    "UuidsBoundEmployeeFilter",
    "UuidsBoundEngagementFilter",
    "UuidsBoundFacetFilter",
    "UuidsBoundITSystemFilter",
    "UuidsBoundITUserFilter",
    "UuidsBoundLeaveFilter",
    "UuidsBoundOrganisationUnitFilter",
    "ValidityInput",
]
