# Generated by ariadne-codegen on 2024-08-22 11:26
# Source: queries.graphql

from typing import List
from uuid import UUID

from .base_model import BaseModel


class TestingGetItSystem(BaseModel):
    itsystems: "TestingGetItSystemItsystems"


class TestingGetItSystemItsystems(BaseModel):
    objects: List["TestingGetItSystemItsystemsObjects"]


class TestingGetItSystemItsystemsObjects(BaseModel):
    uuid: UUID


TestingGetItSystem.update_forward_refs()
TestingGetItSystemItsystems.update_forward_refs()
TestingGetItSystemItsystemsObjects.update_forward_refs()
