# Generated by ariadne-codegen on 2024-10-10 13:36
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class TestingCreateOrgUnitItUser(BaseModel):
    ituser_create: "TestingCreateOrgUnitItUserItuserCreate"


class TestingCreateOrgUnitItUserItuserCreate(BaseModel):
    uuid: UUID


TestingCreateOrgUnitItUser.update_forward_refs()
TestingCreateOrgUnitItUserItuserCreate.update_forward_refs()
