# Generated by ariadne-codegen on 2025-11-06 15:37
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class CreateItUser(BaseModel):
    ituser_create: "CreateItUserItuserCreate"


class CreateItUserItuserCreate(BaseModel):
    uuid: UUID


CreateItUser.update_forward_refs()
CreateItUserItuserCreate.update_forward_refs()
