# Generated by ariadne-codegen on 2024-10-10 13:36
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class DeleteEngagement(BaseModel):
    engagement_delete: "DeleteEngagementEngagementDelete"


class DeleteEngagementEngagementDelete(BaseModel):
    uuid: UUID


DeleteEngagement.update_forward_refs()
DeleteEngagementEngagementDelete.update_forward_refs()
