# Generated by ariadne-codegen on 2025-11-06 15:37
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class DeleteEngagement(BaseModel):
    engagement_delete: "DeleteEngagementEngagementDelete"


class DeleteEngagementEngagementDelete(BaseModel):
    uuid: UUID


DeleteEngagement.update_forward_refs()
DeleteEngagementEngagementDelete.update_forward_refs()
