# Generated by ariadne-codegen on 2025-11-06 15:37
# Source: queries.graphql

from typing import Any
from typing import List
from typing import Optional
from uuid import UUID

from .base_model import BaseModel


class GetEmployeeStates(BaseModel):
    employees: "GetEmployeeStatesEmployees"


class GetEmployeeStatesEmployees(BaseModel):
    objects: List["GetEmployeeStatesEmployeesObjects"]


class GetEmployeeStatesEmployeesObjects(BaseModel):
    validities: List["GetEmployeeStatesEmployeesObjectsValidities"]


class GetEmployeeStatesEmployeesObjectsValidities(BaseModel):
    uuid: UUID
    given_name: str
    surname: str
    nickname_given_name: Optional[str]
    nickname_surname: Optional[str]
    cpr_number: Optional[Any]


GetEmployeeStates.update_forward_refs()
GetEmployeeStatesEmployees.update_forward_refs()
GetEmployeeStatesEmployeesObjects.update_forward_refs()
GetEmployeeStatesEmployeesObjectsValidities.update_forward_refs()
