# Generated by ariadne-codegen on 2024-08-22 17:45
# Source: queries.graphql

from datetime import datetime
from typing import List
from typing import Optional
from uuid import UUID

from pydantic import Field

from .base_model import BaseModel


class GetEmployeeItUsers(BaseModel):
    employees: "GetEmployeeItUsersEmployees"


class GetEmployeeItUsersEmployees(BaseModel):
    objects: List["GetEmployeeItUsersEmployeesObjects"]


class GetEmployeeItUsersEmployeesObjects(BaseModel):
    objects: List["GetEmployeeItUsersEmployeesObjectsObjects"]


class GetEmployeeItUsersEmployeesObjectsObjects(BaseModel):
    itusers: List["GetEmployeeItUsersEmployeesObjectsObjectsItusers"]


class GetEmployeeItUsersEmployeesObjectsObjectsItusers(BaseModel):
    uuid: UUID
    user_key: str
    itsystem: "GetEmployeeItUsersEmployeesObjectsObjectsItusersItsystem"
    person: Optional[List["GetEmployeeItUsersEmployeesObjectsObjectsItusersPerson"]]
    engagement: Optional[
        List["GetEmployeeItUsersEmployeesObjectsObjectsItusersEngagement"]
    ]
    validity: "GetEmployeeItUsersEmployeesObjectsObjectsItusersValidity"


class GetEmployeeItUsersEmployeesObjectsObjectsItusersItsystem(BaseModel):
    uuid: UUID


class GetEmployeeItUsersEmployeesObjectsObjectsItusersPerson(BaseModel):
    uuid: UUID


class GetEmployeeItUsersEmployeesObjectsObjectsItusersEngagement(BaseModel):
    uuid: UUID


class GetEmployeeItUsersEmployeesObjectsObjectsItusersValidity(BaseModel):
    from_: datetime = Field(alias="from")
    to: Optional[datetime]


GetEmployeeItUsers.update_forward_refs()
GetEmployeeItUsersEmployees.update_forward_refs()
GetEmployeeItUsersEmployeesObjects.update_forward_refs()
GetEmployeeItUsersEmployeesObjectsObjects.update_forward_refs()
GetEmployeeItUsersEmployeesObjectsObjectsItusers.update_forward_refs()
GetEmployeeItUsersEmployeesObjectsObjectsItusersItsystem.update_forward_refs()
GetEmployeeItUsersEmployeesObjectsObjectsItusersPerson.update_forward_refs()
GetEmployeeItUsersEmployeesObjectsObjectsItusersEngagement.update_forward_refs()
GetEmployeeItUsersEmployeesObjectsObjectsItusersValidity.update_forward_refs()
