# Generated by ariadne-codegen on 2024-08-22 17:44
# Source: queries.graphql

from typing import Any
from typing import List
from typing import Optional
from uuid import UUID

from .base_model import BaseModel


class GetCurrentEmployeeState(BaseModel):
    employees: "GetCurrentEmployeeStateEmployees"


class GetCurrentEmployeeStateEmployees(BaseModel):
    objects: List["GetCurrentEmployeeStateEmployeesObjects"]


class GetCurrentEmployeeStateEmployeesObjects(BaseModel):
    current: Optional["GetCurrentEmployeeStateEmployeesObjectsCurrent"]


class GetCurrentEmployeeStateEmployeesObjectsCurrent(BaseModel):
    uuid: UUID
    givenname: str
    surname: str
    nickname_givenname: Optional[str]
    nickname_surname: Optional[str]
    cpr_no: Optional[Any]
    seniority: Optional[Any]


GetCurrentEmployeeState.update_forward_refs()
GetCurrentEmployeeStateEmployees.update_forward_refs()
GetCurrentEmployeeStateEmployeesObjects.update_forward_refs()
GetCurrentEmployeeStateEmployeesObjectsCurrent.update_forward_refs()
