# Generated by ariadne-codegen on 2024-08-22 11:26
# Source: queries.graphql

from typing import List
from typing import Optional
from uuid import UUID

from .base_model import BaseModel


class GetClasses(BaseModel):
    facets: "GetClassesFacets"


class GetClassesFacets(BaseModel):
    objects: List["GetClassesFacetsObjects"]


class GetClassesFacetsObjects(BaseModel):
    current: Optional["GetClassesFacetsObjectsCurrent"]


class GetClassesFacetsObjectsCurrent(BaseModel):
    classes: List["GetClassesFacetsObjectsCurrentClasses"]


class GetClassesFacetsObjectsCurrentClasses(BaseModel):
    uuid: UUID
    user_key: str


GetClasses.update_forward_refs()
GetClassesFacets.update_forward_refs()
GetClassesFacetsObjects.update_forward_refs()
GetClassesFacetsObjectsCurrent.update_forward_refs()
GetClassesFacetsObjectsCurrentClasses.update_forward_refs()
