# Generated by ariadne-codegen on 2024-08-22 17:44
# Source: queries.graphql

from datetime import datetime
from typing import List
from typing import Optional
from uuid import UUID

from pydantic import Field

from .base_model import BaseModel


class GetEmployeeAddresses(BaseModel):
    employees: "GetEmployeeAddressesEmployees"


class GetEmployeeAddressesEmployees(BaseModel):
    objects: List["GetEmployeeAddressesEmployeesObjects"]


class GetEmployeeAddressesEmployeesObjects(BaseModel):
    objects: List["GetEmployeeAddressesEmployeesObjectsObjects"]


class GetEmployeeAddressesEmployeesObjectsObjects(BaseModel):
    addresses: List["GetEmployeeAddressesEmployeesObjectsObjectsAddresses"]


class GetEmployeeAddressesEmployeesObjectsObjectsAddresses(BaseModel):
    uuid: UUID
    value: str
    address_type: "GetEmployeeAddressesEmployeesObjectsObjectsAddressesAddressType"
    person: Optional[List["GetEmployeeAddressesEmployeesObjectsObjectsAddressesPerson"]]
    engagement: Optional[
        List["GetEmployeeAddressesEmployeesObjectsObjectsAddressesEngagement"]
    ]
    visibility: Optional[
        "GetEmployeeAddressesEmployeesObjectsObjectsAddressesVisibility"
    ]
    validity: "GetEmployeeAddressesEmployeesObjectsObjectsAddressesValidity"


class GetEmployeeAddressesEmployeesObjectsObjectsAddressesAddressType(BaseModel):
    uuid: UUID


class GetEmployeeAddressesEmployeesObjectsObjectsAddressesPerson(BaseModel):
    uuid: UUID


class GetEmployeeAddressesEmployeesObjectsObjectsAddressesEngagement(BaseModel):
    uuid: UUID


class GetEmployeeAddressesEmployeesObjectsObjectsAddressesVisibility(BaseModel):
    uuid: UUID


class GetEmployeeAddressesEmployeesObjectsObjectsAddressesValidity(BaseModel):
    from_: datetime = Field(alias="from")
    to: Optional[datetime]


GetEmployeeAddresses.update_forward_refs()
GetEmployeeAddressesEmployees.update_forward_refs()
GetEmployeeAddressesEmployeesObjects.update_forward_refs()
GetEmployeeAddressesEmployeesObjectsObjects.update_forward_refs()
GetEmployeeAddressesEmployeesObjectsObjectsAddresses.update_forward_refs()
GetEmployeeAddressesEmployeesObjectsObjectsAddressesAddressType.update_forward_refs()
GetEmployeeAddressesEmployeesObjectsObjectsAddressesPerson.update_forward_refs()
GetEmployeeAddressesEmployeesObjectsObjectsAddressesEngagement.update_forward_refs()
GetEmployeeAddressesEmployeesObjectsObjectsAddressesVisibility.update_forward_refs()
GetEmployeeAddressesEmployeesObjectsObjectsAddressesValidity.update_forward_refs()
