# Generated by ariadne-codegen on 2023-06-13 15:32
# Source: queries.graphql

from typing import List, Optional
from uuid import UUID

from .base_model import BaseModel


class GetEmployees(BaseModel):
    employees: List["GetEmployeesEmployees"]


class GetEmployeesEmployees(BaseModel):
    objects: List["GetEmployeesEmployeesObjects"]


class GetEmployeesEmployeesObjects(BaseModel):
    uuid: Optional[UUID]
    uuid: Optional[UUID]
    user_key: Optional[str]
    name: str
    cpr_no: Optional[str]


GetEmployees.update_forward_refs()
GetEmployeesEmployees.update_forward_refs()
GetEmployeesEmployeesObjects.update_forward_refs()
