# Generated by ariadne-codegen on 2024-10-10 13:36
# Source: queries.graphql

from datetime import datetime
from typing import List
from typing import Optional
from uuid import UUID

from pydantic import Field

from .base_model import BaseModel


class GetEmployeeAddresses(BaseModel):
    employees: "GetEmployeeAddressesEmployees"


class GetEmployeeAddressesEmployees(BaseModel):
    objects: List["GetEmployeeAddressesEmployeesObjects"]


class GetEmployeeAddressesEmployeesObjects(BaseModel):
    validities: List["GetEmployeeAddressesEmployeesObjectsValidities"]


class GetEmployeeAddressesEmployeesObjectsValidities(BaseModel):
    addresses: List["GetEmployeeAddressesEmployeesObjectsValiditiesAddresses"]


class GetEmployeeAddressesEmployeesObjectsValiditiesAddresses(BaseModel):
    uuid: UUID
    value: str
    address_type: "GetEmployeeAddressesEmployeesObjectsValiditiesAddressesAddressType"
    person: Optional[
        List["GetEmployeeAddressesEmployeesObjectsValiditiesAddressesPerson"]
    ]
    engagement: Optional[
        List["GetEmployeeAddressesEmployeesObjectsValiditiesAddressesEngagement"]
    ]
    ituser: List["GetEmployeeAddressesEmployeesObjectsValiditiesAddressesItuser"]
    visibility: Optional[
        "GetEmployeeAddressesEmployeesObjectsValiditiesAddressesVisibility"
    ]
    validity: "GetEmployeeAddressesEmployeesObjectsValiditiesAddressesValidity"


class GetEmployeeAddressesEmployeesObjectsValiditiesAddressesAddressType(BaseModel):
    uuid: UUID


class GetEmployeeAddressesEmployeesObjectsValiditiesAddressesPerson(BaseModel):
    uuid: UUID


class GetEmployeeAddressesEmployeesObjectsValiditiesAddressesEngagement(BaseModel):
    uuid: UUID


class GetEmployeeAddressesEmployeesObjectsValiditiesAddressesItuser(BaseModel):
    uuid: UUID


class GetEmployeeAddressesEmployeesObjectsValiditiesAddressesVisibility(BaseModel):
    uuid: UUID


class GetEmployeeAddressesEmployeesObjectsValiditiesAddressesValidity(BaseModel):
    from_: datetime = Field(alias="from")
    to: Optional[datetime]


GetEmployeeAddresses.update_forward_refs()
GetEmployeeAddressesEmployees.update_forward_refs()
GetEmployeeAddressesEmployeesObjects.update_forward_refs()
GetEmployeeAddressesEmployeesObjectsValidities.update_forward_refs()
GetEmployeeAddressesEmployeesObjectsValiditiesAddresses.update_forward_refs()
GetEmployeeAddressesEmployeesObjectsValiditiesAddressesAddressType.update_forward_refs()
GetEmployeeAddressesEmployeesObjectsValiditiesAddressesPerson.update_forward_refs()
GetEmployeeAddressesEmployeesObjectsValiditiesAddressesEngagement.update_forward_refs()
GetEmployeeAddressesEmployeesObjectsValiditiesAddressesItuser.update_forward_refs()
GetEmployeeAddressesEmployeesObjectsValiditiesAddressesVisibility.update_forward_refs()
GetEmployeeAddressesEmployeesObjectsValiditiesAddressesValidity.update_forward_refs()
