# Generated by ariadne-codegen on 2024-09-09 14:40
# Source: queries.graphql

from typing import List
from typing import Optional
from uuid import UUID

from .base_model import BaseModel


class GetOrgUnitWithItSystemUserKey(BaseModel):
    itusers: "GetOrgUnitWithItSystemUserKeyItusers"


class GetOrgUnitWithItSystemUserKeyItusers(BaseModel):
    objects: List["GetOrgUnitWithItSystemUserKeyItusersObjects"]


class GetOrgUnitWithItSystemUserKeyItusersObjects(BaseModel):
    validities: List["GetOrgUnitWithItSystemUserKeyItusersObjectsValidities"]


class GetOrgUnitWithItSystemUserKeyItusersObjectsValidities(BaseModel):
    org_unit: Optional[
        List["GetOrgUnitWithItSystemUserKeyItusersObjectsValiditiesOrgUnit"]
    ]


class GetOrgUnitWithItSystemUserKeyItusersObjectsValiditiesOrgUnit(BaseModel):
    uuid: UUID


GetOrgUnitWithItSystemUserKey.update_forward_refs()
GetOrgUnitWithItSystemUserKeyItusers.update_forward_refs()
GetOrgUnitWithItSystemUserKeyItusersObjects.update_forward_refs()
GetOrgUnitWithItSystemUserKeyItusersObjectsValidities.update_forward_refs()
GetOrgUnitWithItSystemUserKeyItusersObjectsValiditiesOrgUnit.update_forward_refs()
