# Generated by ariadne-codegen on 2024-08-22 11:26
# Source: queries.graphql

from datetime import datetime
from typing import List
from typing import Optional

from .base_model import BaseModel


class GetOrgUnitValidity(BaseModel):
    org_units: "GetOrgUnitValidityOrgUnits"


class GetOrgUnitValidityOrgUnits(BaseModel):
    objects: List["GetOrgUnitValidityOrgUnitsObjects"]


class GetOrgUnitValidityOrgUnitsObjects(BaseModel):
    objects: List["GetOrgUnitValidityOrgUnitsObjectsObjects"]


class GetOrgUnitValidityOrgUnitsObjectsObjects(BaseModel):
    validity: "GetOrgUnitValidityOrgUnitsObjectsObjectsValidity"


class GetOrgUnitValidityOrgUnitsObjectsObjectsValidity(BaseModel):
    from_date: datetime
    to_date: Optional[datetime]


GetOrgUnitValidity.update_forward_refs()
GetOrgUnitValidityOrgUnits.update_forward_refs()
GetOrgUnitValidityOrgUnitsObjects.update_forward_refs()
GetOrgUnitValidityOrgUnitsObjectsObjects.update_forward_refs()
GetOrgUnitValidityOrgUnitsObjectsObjectsValidity.update_forward_refs()
