# Generated by ariadne-codegen on 2024-08-22 17:44
# Source: queries.graphql

from datetime import datetime
from typing import List
from typing import Optional
from uuid import UUID

from pydantic import Field

from .base_model import BaseModel


class GetEmployeeEngagements(BaseModel):
    employees: "GetEmployeeEngagementsEmployees"


class GetEmployeeEngagementsEmployees(BaseModel):
    objects: List["GetEmployeeEngagementsEmployeesObjects"]


class GetEmployeeEngagementsEmployeesObjects(BaseModel):
    objects: List["GetEmployeeEngagementsEmployeesObjectsObjects"]


class GetEmployeeEngagementsEmployeesObjectsObjects(BaseModel):
    engagements: List["GetEmployeeEngagementsEmployeesObjectsObjectsEngagements"]


class GetEmployeeEngagementsEmployeesObjectsObjectsEngagements(BaseModel):
    uuid: UUID
    user_key: str
    org_unit: List["GetEmployeeEngagementsEmployeesObjectsObjectsEngagementsOrgUnit"]
    person: List["GetEmployeeEngagementsEmployeesObjectsObjectsEngagementsPerson"]
    job_function: "GetEmployeeEngagementsEmployeesObjectsObjectsEngagementsJobFunction"
    engagement_type: (
        "GetEmployeeEngagementsEmployeesObjectsObjectsEngagementsEngagementType"
    )
    primary: Optional["GetEmployeeEngagementsEmployeesObjectsObjectsEngagementsPrimary"]
    validity: "GetEmployeeEngagementsEmployeesObjectsObjectsEngagementsValidity"


class GetEmployeeEngagementsEmployeesObjectsObjectsEngagementsOrgUnit(BaseModel):
    uuid: UUID


class GetEmployeeEngagementsEmployeesObjectsObjectsEngagementsPerson(BaseModel):
    uuid: UUID


class GetEmployeeEngagementsEmployeesObjectsObjectsEngagementsJobFunction(BaseModel):
    uuid: UUID


class GetEmployeeEngagementsEmployeesObjectsObjectsEngagementsEngagementType(BaseModel):
    uuid: UUID


class GetEmployeeEngagementsEmployeesObjectsObjectsEngagementsPrimary(BaseModel):
    uuid: UUID


class GetEmployeeEngagementsEmployeesObjectsObjectsEngagementsValidity(BaseModel):
    from_: datetime = Field(alias="from")
    to: Optional[datetime]


GetEmployeeEngagements.update_forward_refs()
GetEmployeeEngagementsEmployees.update_forward_refs()
GetEmployeeEngagementsEmployeesObjects.update_forward_refs()
GetEmployeeEngagementsEmployeesObjectsObjects.update_forward_refs()
GetEmployeeEngagementsEmployeesObjectsObjectsEngagements.update_forward_refs()
GetEmployeeEngagementsEmployeesObjectsObjectsEngagementsOrgUnit.update_forward_refs()
GetEmployeeEngagementsEmployeesObjectsObjectsEngagementsPerson.update_forward_refs()
GetEmployeeEngagementsEmployeesObjectsObjectsEngagementsJobFunction.update_forward_refs()
GetEmployeeEngagementsEmployeesObjectsObjectsEngagementsEngagementType.update_forward_refs()
GetEmployeeEngagementsEmployeesObjectsObjectsEngagementsPrimary.update_forward_refs()
GetEmployeeEngagementsEmployeesObjectsObjectsEngagementsValidity.update_forward_refs()
