# Generated by ariadne-codegen on 2024-08-22 17:44
# Source: queries.graphql

from typing import List
from typing import Optional
from uuid import UUID

from .base_model import BaseModel


class GetOrgUnitWithItSystemUserKey(BaseModel):
    itusers: "GetOrgUnitWithItSystemUserKeyItusers"


class GetOrgUnitWithItSystemUserKeyItusers(BaseModel):
    objects: List["GetOrgUnitWithItSystemUserKeyItusersObjects"]


class GetOrgUnitWithItSystemUserKeyItusersObjects(BaseModel):
    objects: List["GetOrgUnitWithItSystemUserKeyItusersObjectsObjects"]


class GetOrgUnitWithItSystemUserKeyItusersObjectsObjects(BaseModel):
    org_unit: Optional[
        List["GetOrgUnitWithItSystemUserKeyItusersObjectsObjectsOrgUnit"]
    ]


class GetOrgUnitWithItSystemUserKeyItusersObjectsObjectsOrgUnit(BaseModel):
    uuid: UUID


GetOrgUnitWithItSystemUserKey.update_forward_refs()
GetOrgUnitWithItSystemUserKeyItusers.update_forward_refs()
GetOrgUnitWithItSystemUserKeyItusersObjects.update_forward_refs()
GetOrgUnitWithItSystemUserKeyItusersObjectsObjects.update_forward_refs()
GetOrgUnitWithItSystemUserKeyItusersObjectsObjectsOrgUnit.update_forward_refs()
