# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
# mypy: disable-error-code=assignment
from datetime import datetime
from typing import cast
from unittest.mock import AsyncMock
from unittest.mock import MagicMock
from unittest.mock import call
from uuid import uuid4

from fastramqpi.context import Context

from os2mint_omada.autogenerated_graphql_client import EventSendInput
from os2mint_omada.config import OmadaSettings
from os2mint_omada.omada.event_generator import OMADA_NAMESPACE
from os2mint_omada.omada.event_generator import OMADA_ROUTING_KEY
from os2mint_omada.omada.event_generator import OmadaEventGenerator
from os2mint_omada.omada.models import OmadaEventSubject
from os2mint_omada.omada.models import OmadaUser


def get_test_user(id: int) -> OmadaUser:
    return OmadaUser(
        id=id,
        uid=uuid4(),
        valid_from=datetime(2023, 1, 2),
    )


def subject_builder(omada_user: OmadaUser) -> OmadaEventSubject:
    """Minimal subject builder: these tests only care about which user is emitted."""
    return OmadaEventSubject(id=omada_user.id)


async def test_generate(omada_settings: OmadaSettings) -> None:
    """Test that create/update/delete events are detected correctly."""
    # Arrange
    old_a = get_test_user(1)
    old_b = get_test_user(2)
    old_c = get_test_user(3)
    old_users = [old_a, old_b, old_c]

    new_a = old_a  # A is unchanged
    new_b = old_b.copy(update=dict(id=99))  # B is changed
    new_d = get_test_user(4)  # D is added
    new_users = [new_a, new_b, new_d]  # C is deleted

    # The "API" returns the new users
    api = MagicMock()
    api.get_users = AsyncMock(return_value=new_users)

    graphql_client = AsyncMock()
    context = cast(Context, {"graphql_client": graphql_client})
    event_generator = OmadaEventGenerator(
        settings=omada_settings,
        api=api,
        context=context,
        subject_builder=subject_builder,
    )
    # Override loading from disk to "load" the old users
    event_generator._load_users = MagicMock(return_value=old_users)

    # Act
    await event_generator.generate()

    # Assert: one event per changed user (D created, C deleted, B updated). The
    # change type is no longer encoded in the event, so all share the routing key.
    graphql_client.send_event.assert_has_awaits(
        calls=[
            call(
                input=EventSendInput(
                    namespace=OMADA_NAMESPACE,
                    routing_key=OMADA_ROUTING_KEY,
                    subject=subject_builder(new_d).json(),
                )
            ),
            call(
                input=EventSendInput(
                    namespace=OMADA_NAMESPACE,
                    routing_key=OMADA_ROUTING_KEY,
                    subject=subject_builder(old_c).json(),
                )
            ),
            call(
                input=EventSendInput(
                    namespace=OMADA_NAMESPACE,
                    routing_key=OMADA_ROUTING_KEY,
                    subject=subject_builder(new_b).json(),
                )
            ),
        ],
        any_order=True,
    )
    # The unchanged user A does not produce an event.
    assert graphql_client.send_event.await_count == 3
