# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
# mypy: disable-error-code="no-redef"
import unittest
from collections.abc import AsyncIterator
from collections.abc import Callable
from datetime import datetime
from pathlib import Path
from typing import Awaitable
from unittest.mock import ANY
from uuid import UUID

import pytest
from fastapi.testclient import TestClient
from fastramqpi.events import Event
from fastramqpi.pytest_util import retry
from fastramqpi.pytest_util import retrying
from more_itertools import one
from pydantic import AmqpDsn
from pydantic import AnyHttpUrl
from pydantic import parse_obj_as
from pytest import MonkeyPatch

from os2mint_omada.autogenerated_graphql_client import EngagementCreateInput
from os2mint_omada.autogenerated_graphql_client import GraphQLClient
from os2mint_omada.autogenerated_graphql_client import RAValidityInput
from os2mint_omada.config import OmadaAMQPConnectionSettings
from os2mint_omada.config import OmadaSettings
from os2mint_omada.mo import MO
from os2mint_omada.omada.api import OmadaAPI
from os2mint_omada.omada.api import create_client
from os2mint_omada.sync.silkeborg.address import sync_addresses
from os2mint_omada.sync.silkeborg.engagement import sync_engagements
from os2mint_omada.sync.silkeborg.events import sync_mo_addresses
from os2mint_omada.sync.silkeborg.events import sync_mo_it_users
from os2mint_omada.sync.silkeborg.it_user import sync_it_users
from os2mint_omada.util import MO_TZ

# TODO: Test moving org unit


@pytest.fixture(autouse=True)
def set_customer(monkeypatch: MonkeyPatch) -> None:
    monkeypatch.setenv("CUSTOMER", "silkeborg")


@pytest.fixture
async def org_unit(graphql_client: GraphQLClient) -> UUID:
    # Get org unit type
    result = await graphql_client._testing__get_org_unit_type()
    org_unit_type_uuid = one(result.objects).uuid

    # Create org unit
    user_key = "Silkeborg Kommune"
    org_unit = await graphql_client._testing__create_org_unit(
        user_key=user_key,
        org_unit_type=org_unit_type_uuid,
    )

    return org_unit.uuid


@pytest.mark.integration_test
async def test_silkeborg_manual(
    omada_mock: Callable[[list], None],
    test_client: TestClient,
    graphql_client: GraphQLClient,
    org_unit: UUID,
) -> None:
    # Precondition: The person does not already exist
    cpr_number = "1709933104"
    employee = await graphql_client._testing__get_employee(cpr_number)
    assert employee.objects == []

    # CREATE
    omada_user = {
        # Omada
        "Id": 1041094,
        "UId": "38e4a0f1-1290-40e3-ad83-896abd1d3e50",
        "VALIDFROM": "2012-08-27T00:00:00+02:00",
        "VALIDTO": "2022-12-01T01:00:00+01:00",
        # Employee
        "C_CPRNR": cpr_number,
        # Engagement
        "C_TJENESTENR": "v1216",
        # IT Users
        "C_OBJECTGUID_I_AD": "74dea272-d90b-47c7-8d99-c8efa372fa03",
        "C_LOGIN": "DRV1216",
        # Addresses
        "EMAIL": "Mia.Hansen@silkeborg.dk",
        "C_DIREKTE_TLF": "",
        "CELLPHONE": "12345678",
        "C_INST_PHONE": None,
        # Employee (manual)
        "C_FORNAVNE": "Mia",
        "LASTNAME": "Hansen",
        # Engagement (manual)
        "JOBTITLE": "Medarbejder",
        "C_ORGANISATIONSKODE": str(org_unit),
        "C_SYNLIG_I_OS2MO": False,
    }
    omada_mock([omada_user])

    test_case = unittest.TestCase()
    test_case.maxDiff = None

    @retry()
    async def verify() -> None:
        employees = await graphql_client._testing__get_employee(cpr_number)

        # Employee
        employee_states = one(employees.objects)
        employee = one(employee_states.validities)
        assert employee.cpr_number == cpr_number
        assert employee.given_name == "Mia"
        assert employee.surname == "Hansen"
        assert employee.validity.from_ == datetime(1993, 9, 17, 0, 0, tzinfo=MO_TZ)
        assert employee.validity.to is None

        # Engagement
        test_case.assertCountEqual(
            [e.dict() for e in employee.engagements],
            [
                {
                    "user_key": "v1216",
                    "org_unit": [{"user_key": "Silkeborg Kommune"}],
                    "job_function": {"user_key": "Medarbejder"},
                    "engagement_type": {"user_key": "omada_manually_created_hidden"},
                    "primary": {"user_key": "primary"},
                    "validity": {
                        "from_": datetime(2012, 8, 27, 0, 0, tzinfo=MO_TZ),
                        "to": datetime(2022, 12, 1, 0, 0, tzinfo=MO_TZ),
                    },
                }
            ],
        )

        # Addresses
        test_case.assertCountEqual(
            [a.dict() for a in employee.addresses],
            [
                {
                    "value": "Mia.Hansen@silkeborg.dk",
                    "address_type": {"user_key": "EmailEmployee"},
                    "engagement": [{"user_key": "v1216"}],
                    "ituser": [{"user_key": "DRV1216"}],
                    "visibility": {"user_key": "Public"},
                    "validity": {
                        "from_": datetime(2012, 8, 27, 0, 0, tzinfo=MO_TZ),
                        "to": datetime(2022, 12, 1, 0, 0, tzinfo=MO_TZ),
                    },
                },
                {
                    "value": "12345678",
                    "address_type": {"user_key": "MobilePhoneEmployee"},
                    "engagement": [{"user_key": "v1216"}],
                    "ituser": [{"user_key": "DRV1216"}],
                    "visibility": {"user_key": "Public"},
                    "validity": {
                        "from_": datetime(2012, 8, 27, 0, 0, tzinfo=MO_TZ),
                        "to": datetime(2022, 12, 1, 0, 0, tzinfo=MO_TZ),
                    },
                },
            ],
        )

        # IT Users
        test_case.assertCountEqual(
            [u.dict() for u in employee.itusers],
            [
                {
                    "external_id": "74dea272-d90b-47c7-8d99-c8efa372fa03",
                    "user_key": "74dea272-d90b-47c7-8d99-c8efa372fa03",
                    "itsystem": {"user_key": "omada_ad_guid"},
                    "engagement": [{"user_key": "v1216"}],
                    "validity": {
                        "from_": datetime(2012, 8, 27, 0, 0, tzinfo=MO_TZ),
                        "to": datetime(2022, 12, 1, 0, 0, tzinfo=MO_TZ),
                    },
                },
                {
                    "external_id": "74dea272-d90b-47c7-8d99-c8efa372fa03",
                    "user_key": "DRV1216",
                    "itsystem": {"user_key": "omada_login"},
                    "engagement": [{"user_key": "v1216"}],
                    "validity": {
                        "from_": datetime(2012, 8, 27, 0, 0, tzinfo=MO_TZ),
                        "to": datetime(2022, 12, 1, 0, 0, tzinfo=MO_TZ),
                    },
                },
            ],
        )

    await verify()

    # EDIT
    updated_omada_user = {
        **omada_user,
        # Addresses
        "EMAIL": "Alice@silkeborg.dk",
        "C_DIREKTE_TLF": "19890604",
        "CELLPHONE": None,  # deleted
        # IT Users
        "C_LOGIN": "VB18210",
        # Employee (manual)
        "C_FORNAVNE": "Alice",
        # Engagement (manual)
        "JOBTITLE": "Something That Doesn't Exist in MO",
        "C_SYNLIG_I_OS2MO": True,
    }
    omada_mock([updated_omada_user])

    @retry()
    async def verify() -> None:
        employees = await graphql_client._testing__get_employee(cpr_number)

        # Employee
        employee_states = one(employees.objects)
        employee = one(employee_states.validities)
        # Existing employees in Silkeborg must never be modified, so the name should be
        # unchanged.
        assert employee.given_name == "Mia"

        # Engagement
        test_case.assertCountEqual(
            [e.dict() for e in employee.engagements],
            [
                {
                    "user_key": "v1216",
                    "org_unit": [{"user_key": "Silkeborg Kommune"}],
                    "job_function": {"user_key": "not_applicable"},
                    "engagement_type": {"user_key": "omada_manually_created"},
                    "primary": {"user_key": "primary"},
                    "validity": {
                        "from_": datetime(2012, 8, 27, 0, 0, tzinfo=MO_TZ),
                        "to": datetime(2022, 12, 1, 0, 0, tzinfo=MO_TZ),
                    },
                },
            ],
        )

        # Addresses
        assert {a.value for a in employee.addresses} == {
            "Alice@silkeborg.dk",
            "19890604",
        }

        # IT Users
        assert {(u.external_id, u.user_key) for u in employee.itusers} == {
            (
                "74dea272-d90b-47c7-8d99-c8efa372fa03",
                "74dea272-d90b-47c7-8d99-c8efa372fa03",
            ),
            (
                "74dea272-d90b-47c7-8d99-c8efa372fa03",
                "VB18210",
            ),
        }

    await verify()

    # DELETE
    omada_mock([])

    @retry()
    async def verify() -> None:
        employees = await graphql_client._testing__get_employee(cpr_number)
        employee_states = one(employees.objects)
        employee = one(employee_states.validities)
        assert employee.engagements == []
        assert employee.addresses == []
        assert employee.itusers == []

    await verify()


@pytest.mark.integration_test
async def test_silkeborg_sd_user(
    omada_mock: Callable[[list], None],
    test_client: TestClient,
    graphql_client: GraphQLClient,
    org_unit: UUID,
) -> None:
    # Precondition: The person does not already exist
    cpr_number = "1709933104"
    employees = await graphql_client._testing__get_employee(cpr_number)
    assert employees.objects == []

    # The user starts as a manual user
    omada_user = {
        # Omada
        "Id": 1041094,
        "UId": "38e4a0f1-1290-40e3-ad83-896abd1d3e50",
        "VALIDFROM": "2012-08-27T00:00:00+02:00",
        "VALIDTO": "2022-12-01T01:00:00+01:00",
        # Employee
        "C_CPRNR": cpr_number,
        # Engagement
        "C_TJENESTENR": "v1216",
        "C_OS2MO_ID": None,
        # IT Users
        "C_OBJECTGUID_I_AD": "74dea272-d90b-47c7-8d99-c8efa372fa03",
        "C_LOGIN": "DRV1216",
        # Addresses
        "EMAIL": "Mia.Hansen@silkeborg.dk",
        "C_DIREKTE_TLF": None,
        "CELLPHONE": None,
        "C_INST_PHONE": None,
        # Employee (manual)
        "C_FORNAVNE": "Mia",
        "LASTNAME": "Hansen",
        # Engagement (manual)
        "JOBTITLE": "Medarbejder",
        "C_ORGANISATIONSKODE": str(org_unit),
        "C_SYNLIG_I_OS2MO": False,
    }
    omada_mock([omada_user])

    test_case = unittest.TestCase()
    test_case.maxDiff = None

    async for attempt in retrying():
        with attempt:
            employees = await graphql_client._testing__get_employee(cpr_number)

            # Employee
            employee_states = one(employees.objects)
            employee = one(employee_states.validities)

            # Engagement
            test_case.assertCountEqual(
                [e.dict() for e in employee.engagements],
                [
                    {
                        "user_key": "v1216",
                        "org_unit": ANY,
                        "job_function": {"user_key": "Medarbejder"},
                        "engagement_type": {
                            "user_key": "omada_manually_created_hidden"
                        },
                        "primary": {"user_key": "primary"},
                        "validity": ANY,
                    }
                ],
            )

            # Addresses
            test_case.assertCountEqual(
                [a.dict() for a in employee.addresses],
                [
                    {
                        "value": ANY,
                        "address_type": ANY,
                        "engagement": [{"user_key": "v1216"}],
                        "ituser": [{"user_key": "DRV1216"}],
                        "visibility": ANY,
                        "validity": ANY,
                    },
                ],
            )

            # IT Users
            test_case.assertCountEqual(
                [u.dict() for u in employee.itusers],
                [
                    {
                        "external_id": "74dea272-d90b-47c7-8d99-c8efa372fa03",
                        "user_key": "74dea272-d90b-47c7-8d99-c8efa372fa03",
                        "itsystem": {"user_key": "omada_ad_guid"},
                        "engagement": [{"user_key": "v1216"}],
                        "validity": ANY,
                    },
                    {
                        "external_id": "74dea272-d90b-47c7-8d99-c8efa372fa03",
                        "user_key": "DRV1216",
                        "itsystem": {"user_key": "omada_login"},
                        "engagement": [{"user_key": "v1216"}],
                        "validity": ANY,
                    },
                ],
            )

    mo = MO(graphql_client)
    employee_uuid = await mo.get_employee_uuid_from_cpr(cpr_number)
    engagement_types = await mo.get_classes("engagement_type")
    engagement_job_functions = await mo.get_classes("engagement_job_function")

    # Then, it is imported from SD
    await graphql_client.create_engagement(
        input=EngagementCreateInput(
            user_key="DK-1337",
            person=employee_uuid,
            org_unit=org_unit,
            engagement_type=engagement_types["deltid"],
            job_function=engagement_job_functions["Medarbejder"],
            validity=RAValidityInput(
                from_=datetime(2015, 5, 5, tzinfo=MO_TZ),
                to=datetime(2025, 5, 5, tzinfo=MO_TZ),
            ),
        )
    )
    # And omada is changed to a non-manual user
    updated_omada_user = {
        **omada_user,
        "C_OS2MO_ID": "DK-1337",
    }
    omada_mock([updated_omada_user])

    async for attempt in retrying():
        with attempt:
            employees = await graphql_client._testing__get_employee(cpr_number)
            employee_states = one(employees.objects)
            employee = one(employee_states.validities)

            # The omada engagement should be deleted
            test_case.assertCountEqual(
                [e.dict() for e in employee.engagements],
                [
                    {
                        "user_key": "DK-1337",
                        "org_unit": ANY,
                        "job_function": {"user_key": "Medarbejder"},
                        "engagement_type": {"user_key": "deltid"},
                        "primary": None,
                        "validity": ANY,
                    }
                ],
            )

            # And all objects should be associated with the SD engagement
            test_case.assertCountEqual(
                [a.dict() for a in employee.addresses],
                [
                    {
                        "value": ANY,
                        "address_type": ANY,
                        "engagement": [{"user_key": "DK-1337"}],
                        "ituser": [{"user_key": "DRV1216"}],
                        "visibility": ANY,
                        "validity": ANY,
                    },
                ],
            )
            test_case.assertCountEqual(
                [u.dict() for u in employee.itusers],
                [
                    {
                        "external_id": ANY,
                        "user_key": ANY,
                        "itsystem": {"user_key": "omada_ad_guid"},
                        "engagement": [{"user_key": "DK-1337"}],
                        "validity": ANY,
                    },
                    {
                        "external_id": ANY,
                        "user_key": ANY,
                        "itsystem": {"user_key": "omada_login"},
                        "engagement": [{"user_key": "DK-1337"}],
                        "validity": ANY,
                    },
                ],
            )


@pytest.mark.integration_test
async def test_silkeborg_user_refresh(
    omada_mock: Callable[[list], None],
    test_client: TestClient,
    graphql_client: GraphQLClient,
    org_unit: str,
    get_num_queued_messages: Callable[[], Awaitable[int]],
) -> None:
    invalid_cpr = "0000000000"
    valid_cpr = "1604650441"

    # Precondition: The person does not already exist
    employee = await graphql_client._testing__get_employee(valid_cpr)
    assert employee.objects == []
    # Precondition: There are no messages in the AMQP queues
    assert await get_num_queued_messages() == 0

    # Serve invalid Omada user
    omada_user = {
        # Omada
        "Id": 666,
        "UId": "73a04b28-9c4a-4b1c-82fa-76705a656341",
        "VALIDFROM": "2006-06-06T00:00:00+01:00",
        "VALIDTO": "2012-12-12T00:00:00+01:00",
        # Employee
        "C_CPRNR": invalid_cpr,
        # Engagement
        "C_TJENESTENR": "v666",
        # IT Users
        "C_OBJECTGUID_I_AD": "74dea272-d90b-47c7-8d99-c8efa372fa03",
        "C_LOGIN": "DRV1216",
        # Employee (manual)
        "C_FORNAVNE": "Kashigi",
        "LASTNAME": "Yabushige",
        # Engagement (manual)
        "JOBTITLE": "Medarbejder",
        "C_ORGANISATIONSKODE": org_unit,
        "C_SYNLIG_I_OS2MO": False,
    }
    omada_mock([omada_user])

    @retry()
    async def verify() -> None:
        # Ensure the user was picked up by the event generator
        assert await get_num_queued_messages() >= 1

    await verify()

    # Serve corrected Omada user
    corrected_omada_user = {
        **omada_user,
        "C_CPRNR": valid_cpr,
    }
    omada_mock([corrected_omada_user])

    @retry()
    async def verify() -> None:
        # The invalid user from the queue should be disregarded in favour of updated
        # data (with valid CPR) directly from Omada.
        employees = await graphql_client._testing__get_employee(valid_cpr)
        assert employees.objects
        assert await get_num_queued_messages() == 0

    await verify()


@pytest.fixture
async def omada_api(tmp_path: Path) -> AsyncIterator[OmadaAPI]:
    """
    A real OmadaAPI whose HTTP calls are intercepted by the `omada_mock`.
    """
    settings = OmadaSettings(
        url=parse_obj_as(AnyHttpUrl, "http://fake-omada-api/"),
        amqp=OmadaAMQPConnectionSettings(
            url=parse_obj_as(AmqpDsn, "amqp://guest:guest@msg-broker:5672/"),
        ),
        persistence_file=tmp_path / "omada.json",
    )
    client = create_client(settings)
    async with client:
        yield OmadaAPI(url=settings.url, client=client)


def _omada_user(org_unit: UUID) -> dict:
    return {
        # Omada
        "Id": 1041094,
        "UId": "38e4a0f1-1290-40e3-ad83-896abd1d3e50",
        "VALIDFROM": "2012-08-27T00:00:00+02:00",
        "VALIDTO": "2022-12-01T01:00:00+01:00",
        # Employee
        "C_CPRNR": "1709933104",
        # Engagement
        "C_TJENESTENR": "v1216",
        # IT Users
        "C_OBJECTGUID_I_AD": "74dea272-d90b-47c7-8d99-c8efa372fa03",
        "C_LOGIN": "DRV1216",
        # Addresses
        "EMAIL": "Mia.Hansen@silkeborg.dk",
        "C_DIREKTE_TLF": "",
        "CELLPHONE": "12345678",
        "C_INST_PHONE": None,
        # Employee (manual)
        "C_FORNAVNE": "Mia",
        "LASTNAME": "Hansen",
        # Engagement (manual)
        "JOBTITLE": "Medarbejder",
        "C_ORGANISATIONSKODE": str(org_unit),
        "C_SYNLIG_I_OS2MO": False,
    }


async def _sync_omada_user(
    graphql_client: GraphQLClient, mo: MO, omada_api: OmadaAPI
) -> UUID:
    """
    Create the managed engagement, IT-users and addresses for the employee,
    exactly as the Omada-side sync does, and return the employee UUID.
    """
    employee = await graphql_client._testing__create_employee(
        cpr_number="1709933104", given_name="Mia", surname="Hansen"
    )
    await sync_engagements(employee.uuid, mo, omada_api)
    await sync_it_users(employee.uuid, mo, omada_api)
    await sync_addresses(employee.uuid, mo, omada_api)
    return employee.uuid


@pytest.mark.integration_test
async def test_sync_it_users_after_engagement_delete(
    omada_mock: Callable[[list], None],
    graphql_client: GraphQLClient,
    omada_api: OmadaAPI,
    org_unit: UUID,
) -> None:
    """
    A deleted engagement is handled the whole way through.

    The MO event for a deleted engagement carries only the engagement's own
    UUID, but the employee is still resolved from its registrations, so the
    handler runs sync_it_users and synchronises the now-undesired IT-users away.
    """
    mo = MO(graphql_client)
    it_systems = await mo.get_it_systems(["omada_ad_guid", "omada_login"])

    # Arrange: managed engagement, IT-users and addresses exist for the employee.
    omada_mock([_omada_user(org_unit)])
    employee_uuid = await _sync_omada_user(graphql_client, mo, omada_api)
    engagement_uuid = one(await mo.get_employee_engagements(employee_uuid)).uuid
    assert engagement_uuid is not None
    assert await mo.get_employee_it_users(employee_uuid, list(it_systems.values()))

    # Act: the engagement is deleted, and its event is handled while no Omada user
    # is served (so the desired state is empty).
    omada_mock([])
    await graphql_client.delete_engagement(uuid=engagement_uuid)
    await sync_mo_it_users(
        Event[UUID](subject=engagement_uuid, priority=0), mo, omada_api
    )

    # Assert: the handler resolved the employee and synchronised their IT-users away.
    assert not await mo.get_employee_it_users(employee_uuid, list(it_systems.values()))


@pytest.mark.integration_test
async def test_sync_addresses_after_ituser_delete(
    omada_mock: Callable[[list], None],
    graphql_client: GraphQLClient,
    omada_api: OmadaAPI,
    org_unit: UUID,
) -> None:
    """
    A deleted IT-user is handled the whole way through.

    The MO event for a deleted IT-user carries only the IT-user's own UUID, but
    the employee is still resolved from its registrations, so the handler runs
    sync_addresses and synchronises the now-undesired addresses away.
    """
    mo = MO(graphql_client)
    address_types = list((await mo.get_classes("employee_address_type")).values())
    omada_login = (await mo.get_it_systems(["omada_login"]))["omada_login"]

    # Arrange: managed engagement, IT-users and addresses exist for the employee.
    omada_mock([_omada_user(org_unit)])
    employee_uuid = await _sync_omada_user(graphql_client, mo, omada_api)
    ituser_uuid = one(await mo.get_employee_it_users(employee_uuid, [omada_login])).uuid
    assert ituser_uuid is not None
    assert await mo.get_employee_addresses(employee_uuid, address_types)

    # Act: the IT-user is deleted, and its event is handled while no Omada user is
    # served (so the desired state is empty).
    omada_mock([])
    await graphql_client.delete_it_user(uuid=ituser_uuid)
    await sync_mo_addresses(Event[UUID](subject=ituser_uuid, priority=0), mo, omada_api)

    # Assert: the handler resolved the employee and synchronised their addresses away.
    assert not await mo.get_employee_addresses(employee_uuid, address_types)
